spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: '${GITHUB_REPO}'
          username: '${GITHUB_USER}'
          password: '${GITHUB_PASS}'
server:
  port: '8888'
